name: app-person

services:
    db:
        container_name: postgres-db
        image: postgres:18
        restart: always
        # ports:
        #     - 35432:5432
        environment:
            POSTGRES_DB: $DB_NAME
            POSTGRES_USER: $DB_USER
            POSTGRES_PASSWORD: $DB_PWD
        volumes:
            - postgresdata:/var/lib/postgresql
            - ./db/init:/docker-entrypoint-initdb.d
        networks:
            - api-db-network
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 1GB
                reservations:
                    cpus: '0.50'
                    memory: 500M
    back:
        container_name: express-api
        build: ./back
        ports:
            - 33000:3000
        environment:
            DB_HOST: db
            DB_NAME: $DB_NAME
            DB_PORT: 5432
            DB_USER: $DB_USER
            DB_PASSWORD: $DB_PWD
        networks:
            - api-db-network
        depends_on:
            - db
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 1GB
                reservations:
                    cpus: '0.50'
                    memory: 500M

volumes:
    postgresdata:

networks:
    api-db-network:
